### ISSUE TITLE
Add an "Export with Calibrations" selection to Config/Constant entries in Part Templates

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#119]
@MarioCarloni 
Add an "Export with Calibrations" column containing a check-box (boolean) selector to the Update Configurations/Constants tool in Part Templates, kind of like in the marked-up image below.
(The colors I used don't matter... I just didn't feel like fighting with Gimp any more than I had to to get the point across.)
This will help @sbatchelder more easily determine which Configs and Constants need to get exported alongside of the Calibrations for the GitHub CSVs.

@sbatchelder - Do we need to also add this boolean by default to all of the Calibrations in the Part Template for your exports to work smoothly? I'm thinking no, because we are assuming that we will always want to export all Calibration items that are in the Part Template, and those are separate enough from Configs/Constants that you don't need an "Export with Calibrations" field to identify them. Please confirm whether that is sufficient, or if you would like that field on all Calibrations as well.

![Screenshot from 2020-08-03 12-10-00](https://user-images.githubusercontent.com/11924613/89204712-8dd27200-d584-11ea-86cf-4e49e5935cfa.png)

**Comment by sbatchelder** [comment]
An "Export with Calibrations" or "Include in Calibrations Export" on the config/const model is enough!

**Comment by sbatchelder** [comment]
Do the Config/Consts to be exported along with Calibrations need to be included in the same csv? Right now i'm exporting them on a CalibrationEvent and ConfigEvent basis. 

If yes (which I think is the desired behavior), then which of any ConfigEvents for a given instrument should be the one to include? 
(A) The most recent ConfigEvent overall ( because there really should be only one config/constant field event per instrument, since the values are invariant.... right?? I think right now it IS possible to associate multiple ConfigEvents with an instrument/inventory )
(B) only ConfigEvents with the same date as the CalibrationEvent
(C) the closest ConfigEvent  to the CalibrationEvent by date (forwards and backwards in time)
(V) as B), but backwards in time only. 
(E) some way of explicitly associating the ConfigEvent to a CalibrationEvent?

(A) or (C) seem the most viable, but depends on your use-case.

Aside:
It might be easier to associate the "Include in Calibration Exports" flag with the ConfigEvent rather than individual/sub the ConfigValue or ConfigName, but I don't know if that satisfies your use-case. What do you think Steph?

**Comment by spetillo** [comment]
@sbatchelder GOOD questions.

> Do the Config/Consts to be exported along with Calibrations need to be included in the same csv?

Yes.

Note:

- Constant Events are invariant. Config Events can change, and are entered on a per-deployment basis. 

- Config Events will _almost_ never have the same date as a Calibration Event.

Answer: (C), but _forward_ in time only.

Explanation/Details:

- If an instrument type exports any Config or Constant information with the Calibration CSVs (or _as_ the Calibration CSVs, because some instruments, like METBK, don't actually contain any Calibration values), then the Config Event's (Deployment) date is used in the Exported CSV file name, and the most recent Calibration Event _backwards_ in time from the Config Event (Deployment) date gets included.

- Inverting the explanation in the last bullet (sort of) to better align with how you asked the question: Calibration Events should be associated with the next Configuration Events (plural!) _forward_ in time, _until_ the next Calibration Event date forward in time is reached. (I.e., it may not always be 1-to-1 for Calibration Events & Config Events. There can be multiple Config Events per Calibration Event, but _not_ vice versa.) 

> Aside:
> It might be easier to associate the "Include in Calibration Exports" flag with the ConfigEvent rather than individual/sub the ConfigValue or ConfigName, but I don't know if that satisfies your use-case. What do you think Steph?

Unfortunately, that won't work, since there will be a mixture of Config Names in a single Config Event that both will and won't need to be included in the Calibration Exports. There could, however, be a roll-up flag (internal to the DB) on the Config Event that indicates whether _one or more_ Config Names in the config event should be included with the Calibration CSV Export.

**Comment by sbatchelder** [comment]
ok, so i think i have a handle on it. There are several cases, but each case will probably starts the same: generate a collection of CalibEvents and ConfigEvents-with-"export-with-CalibEvent"-rollup-flag, ordered by date on a per-instrument basis. The collection is then looped over from most-to-least-recent. Here's how I think I can handle the csv generation:

1. just CalibEvents: simple, one csv per CalibEvent, with maybe some auxiliary files for 2d values.
2. there's a mix of calibration and config events: 
2a. create a csv dated by the first/next encountered object (since we're going from most-to-least recent, if there's a mix it would be a ConfigEvent). Add "export-with-CalibEvent" ConfigValues to csv.
2b. continue adding ConfigEvent ConfigValues to the csv until a CalibEvent is reached. Add values from the CalibEvent and finish the csv. 
2c. continue looping, go back to (2a).
3. just ConfigEvents (eg METBK): **ambiguous**, do they all get... 
3a. rolled up into one csv? 
3b. each get a separate csv? 
3c. collected into difference csv's somehow? Perhaps start a new csv when a ConfigEvent with an already csv'd config field name is encountered?

Is the creation of a csv with duplicate ~~config~~ field names (eg from different ConfigEvents) explicitly illegal? If (3c) is the way to go, does this new-csv creation mode apply to (2) as well? (I'm looking to generalize, as it's totally possible for there to be missing data, like a missing CalibEvent which would throw off the csv-demarcation-by-CalibEvent method)

**Comment by spetillo** [comment]
In response to @sbatchelder 's previous post...

1. Correct
2. I'm unclear on (2a). What needs to be done should be able to be summarized by (2b), but also accounting for one more edge case: When there's a mix of Config and Calib Events, start with the most recent Config Event (adding all config values in _that Config Event only_) and then add in the most recent Calib Event that happened before that Config Event. This will be dated by the date on the Config Event. (Pretty sure this is what you were saying in (2a).) Edge case: if you have _two_ Config Events more recent than a Calib Event, then _two_ CSVs get created. Each of these CSVs will be dated by the Config Event's date, and they will include _only_ that Config Event's data, plus the most recent Calib Event's data.

For example: 

Config Events:
- 2020/08/11
- 2020/06/28
- 2019/02/02

Calib Events:
- 2019/10/22
- 2018/11/30

Resulting CSVs:
- 2020/08/11 (includes Config 2020/08/11 + Cal 2019/10/22)
- 2020/06/28 (includes Config 2020/06/28 + Cal 2019/10/22)
- 2019/02/02 (includes Config 2019/02/02 + Cal 2018/11/30)

3. (3b)... Each Config Event gets a separate CSV.

> Is the creation of a csv with duplicate config field names (eg from different ConfigEvents) explicitly illegal?

Yes, that's illegal.

> If (3c) is the way to go, does this new-csv creation mode apply to (2) as well?

(We're not going with (3c).)

>  (I'm looking to generalize, as it's totally possible for there to be missing data, like a missing CalibEvent which would throw off the csv-demarcation-by-CalibEvent method)

This should be avoided with my clarification of handling (2) above.

> What behavior do you want for Config/Constats Bulk Export, something like whatever we resolve for (3) from above? Is this a feature that's even needed/wanted, seeing as it's outside of the CI github-csv scope)

Config/Const Bulk Export would be like (3b)... a CSVs for each Config Event (i.e., Deployment). The file naming and conglomeration (or at least the directory structure we put the exported files in) would be different from the Calib Bulk Exports as well, since it would be useful to group the Config files under a folder named for the Cruise and/or Platform/Deployment#/subassembly it was deployed on.

For example (this is in no way set in stone):

- config_bulk_exports/pioneer13/cp01cnsm/d0011/mfn/CGINS-ADCPSL-13992.cfg
- config_bulk_exports/pioneer13/cp01cnsm/d0011/nsif/CGINS-CTDBPF-50001.cfg
- config_bulk_exports/pioneer12/cp01cnsm/d0010/mfn/CGINS-ADCPSL-12345.cfg
OR
- config_bulk_exports/cp01cnsm/d0011/mfn/CGINS-ADCPSL-13992.cfg
- config_bulk_exports/cp01cnsm/d0011/nsif/CGINS-CTDBPF-50001.cfg
- config_bulk_exports/cp01cnsm/d0010/mfn/CGINS-ADCPSL-12345.cfg

We're also going to need to have some custom Exports for Config Events, which I would like to use to replace the `platform.cfg` files (used in the mooring software) for each mooring, and to create other/new types of config files for the moorings. We may need to come up with a custom tagging/flagging system for Config/Constant Names that would enable the creation of Custom Exports without needing to hard-code every Custom Export case, kind of like the use of the "export-with-CalibEvent" flag. This could be a pretty sweet Custom Export Builder feature (that would be outside of the CI integration scope).

**Comment by spetillo** [comment]
Change "if there are multiple calib events after it" to "if there are multiple **config** events after it".

**And** we can't forget **Constants**... some of which (indicated by the "export-with-CalibEvent" flag) will also get exported with the calibrations & configs. Constants should be, well, constant, so they would not change and (if flagged) get added to the Exported Calib CSVs.

**Comment by spetillo** [comment]
The "Export with CSV" boxes have been added. some further work is needed on the Bulk Export [CI] side, which will be addressed in ticket #148 . I'm calling this ticket good to go.
