### ISSUE TITLE
Configs/Constants Search Results are Incorrect

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#159]
Config/Constants Search is missing expected results.  Seems like Search isn't finding recently added records.  Here's one example:

Looking at first Record in Configuration Hstory for 3305-00012-00001-01329 (a PRESF-A instrument), "CONFIG1" is "4444"

![image](https://user-images.githubusercontent.com/14059724/92032427-200e9700-ed38-11ea-9f97-0f72b4b381f9.png)

Searching for "CONFIG1" returns some results, but not 3305-00012-00001-01329

![image](https://user-images.githubusercontent.com/14059724/92032482-34eb2a80-ed38-11ea-9056-cbf9f26dea4b.png)

No results when Searching "Value" and "Notes" for "44"

![image](https://user-images.githubusercontent.com/14059724/92033028-fe61df80-ed38-11ea-93c9-2e52280fedd2.png)

**Comment by ethanandrews** [comment]
These changes are up on staging and testing for review

**Comment by cahearn** [comment]
Tested good on Staging!  Updates to C/C/C are now returned in Search.  Did find a hiccup in results, but seems 50/50 that we'll pin it on issues with data on Staging...
Search for config6 returns 2 results for CGINS-DOSTAD-00126, but there's only one record shown.

---
![image](https://user-images.githubusercontent.com/14059724/92830413-49b46780-f3a3-11ea-840c-6dfecc8a23e4.png)

---

![image](https://user-images.githubusercontent.com/14059724/92830723-9b5cf200-f3a3-11ea-8cc0-2cb423dc216d.png)

**Comment by sbatchelder** [comment]
That is curious. I have a less up-to-date version and this is what mine looks like.
**One search result returned** BUT the inventory calibration history tab is **empty**:

![image](https://user-images.githubusercontent.com/44208509/93100458-2b868a00-f677-11ea-9ec7-92f561013990.png)
I thought maybe it's a record that was previously deleted but still searchable... but thats not the case. I created a configuration, saw that it appeared in search, deleted it, and it then no longer appeared in search. *So it's something else.*

In the db the ID of this "ghost calibration event" is **id#25**. Here's the downloaded content from it

![image](https://user-images.githubusercontent.com/44208509/93101927-e19ea380-f678-11ea-907e-52de5ee1e3cd.png)

I'm looping Mario into this one, since he might have an idea of whats going on with this particular bug.
_Or maybe this should be a new issue??_

For reference, this is the browser's console window output

![image](https://user-images.githubusercontent.com/44208509/93102355-6689bd00-f679-11ea-9bbf-aba598ce4a62.png)

And the corresponding error server side:

![image](https://user-images.githubusercontent.com/44208509/93102594-9afd7900-f679-11ea-9b90-9fba0f31857d.png)
