### ISSUE TITLE
Download CSV for Part Tempate contains malformed Custom Field

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#166]
When Downloading a CSV for Part Templates, the Custom Field (Default) is exported as "G,o,o,d" when it should be "Good".

Why is the Default value exported and not the Actual Custom Field value assigned?

**Comment by sbatchelder** [comment]
The Default value is reported because Part Templates may be initiated with a default value. These default values are used when creating a Inventory item based off the templates. At the Inventory level, the default values may then also be overwritten.

This does pose a question: in a Part Templates search result (incl. download), how does one differentiate between a blank `""` default value and a non-existent UDF column for a given Part Template (given that different templates will have different UDFs, any of which's default values could be blank).

How about any Part Template that does not feature a particular UDF column gets a `―`

![image](https://user-images.githubusercontent.com/44208509/93124943-6947da80-f698-11ea-9775-452ebb242856.png)

**Comment by ethanandrews** [comment]
Fix for this is up on staging and testing

**Comment by joannekoch** [comment]
Verified the fix for this issue is working on staging. Added the question, "Why is the Default value exported and not the Actual Custom Field value assigned?" to issue #170 to Revisit the workings/design of the Custom Fields.
