### ISSUE TITLE
Expand Reviewer search to add C/C/C Names & Defaults, Deployments, etc.

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#199]
Reviewer search works for C/C/C Events, and we should add a Reviewer search for C/C/C Names & Defaults.

Ultimately, a Reviewer needs to be able to search for their name in one place, and it should come up with one list of all Events, Part Templates (where Names are entered), and Defaults, plus anything else that has Reviewer/Approver functionality, like Deployment info.

**Comment by sbatchelder** [comment]
@spetillo @cahearn 
Here's what the search results look like. Have I missed anything?

Note: for this screencap I limited results to two per table, and there's two users shown because Steph you had a number of CCC records and Ethan had a number of Action records but neither had both.

![image](https://user-images.githubusercontent.com/44208509/101704467-d0d0b480-3a52-11eb-987b-4e5e548bec03.png)
![image](https://user-images.githubusercontent.com/44208509/101704514-ed6cec80-3a52-11eb-883e-389f24860eee.png)

**Comment by sbatchelder** [comment]
@ethanandrews 
I'm having a hard time creating a link to a deployment details view for the Deployment Actions table. `url = reverse('deployments:deployment_detail',deployment.pk)` fails despite `roundabout/inventory/urls_deployment.py` existing, so that "app" must not be active.

I tried to emulate what the builds detail view does with anchors as show below, but this fails I think because since the page is dynamically built with ajax the anchor doesn't exist on-load.
`url = reverse("builds:builds_detail", args=[build_pk])+"#deployment-{deployment_pk}-"`

The closest I've figured out is to do `url = reverse("builds:builds_detail", args=[build_pk])+"#deployments"` which at least gets the user to a the deployments tab.

If you know of a better way to link directly to a deployment view I'd love to hear it!
Otherwise, if this behavior is sufficient, it can be left as-is.

**Comment by ethanandrews** [comment]
I think this is the best solution for the moment. There’s currently no discrete “Deployments” interface that can be viewed for a single Deployment like that, Deployments are just sub-data for Builds.

We can build a new interface for Deployments, but that would definitely be a new task.

**Comment by sbatchelder** [comment]
Are CCC Value-Events something different from a **Calibration Events** and **Config Events** (CCC Events)? 

CCC Events contain a collection of CoefficientValue and ConfigValue objects respectively (CCC Values), but CCC Value objects do not have their own `user_draft`, `user_reviewer`, and `approved` fields. Only CCC Events,  CCC Name-Events, and CC Default-Events have those (as-per `roundabout/calibrations/models.py` and `roundabout/configs_constants/models.py`)

**Comment by spetillo** [comment]
@sbatchelder Yup, you're right! Individual CCC Values don't have specific Reviewers/Approvers attached to them. I was thinking of an entirely different feature when I said that. Sorry, you can ignore my comment above!!! :zipper_mouth_face: 

Looks good as-is!
