### ISSUE TITLE
Allow retroactive addition of Constant & Configuration Events while Build/Inventory is not actively deployed, if feasible

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#208]
We can edit existing Constant & Configuration Events in history right now, but we can only add them during a deployment. After going through testing and usage, I have found that it would be much easier to use if - at any time - we can add Constant Events to Inventory Parts and Configuration Events to Builds.

I'm not sure if this is possible/feasible due to the ability and need to move inventory on and off of builds, etc. Also, the need for this may wane once we get all historical deployments and calibration CSVs imported into RDB.

**Comment by joannekoch** [comment]
Perhaps I don't understand this enhancement, but if I have the following Inventory not actively deployed:

![Capture](https://user-images.githubusercontent.com/65416034/109991122-08f53580-7cd8-11eb-9ae6-06da9d873b6b.PNG)

And I Edit Constant Values and try to Add a Constant, the dropdown row "scnst12" is added and there is nothing else to pick from the dropdown. This error message is displayed and I can't add anything else:

![Capture1](https://user-images.githubusercontent.com/65416034/109991560-6ab59f80-7cd8-11eb-91ec-4bd731f8f6c0.PNG)

When I then added "scnst13" Constant to the Part Template and I added a value to the Constant Default for "scnst13" to the Inventory item, I still only had the option to add  "scnst12" to the Inventory Constant History.

Also, I get the same result when the Inventory is actively deployed.

**Comment by MarioCarloni** [comment]
The feature was to allow Config or Constant Events to be entered for an Inventory item (using the "Choose Action" dropdown from the Inventory detail page) regardless of whether the associated Build was Deployed or not.

The error message above I believe is correctly shown, where two Constants of the same name are entered in the Event, which is not allowed. However, since the Events are now driven by existing Configs or Constants (and respective Defaults), the "Add Constants" and "Add Configs" buttons should be removed from the Event form. I can make an additional enhancement to remove those buttons.

**Comment by cahearn** [comment]
This works great, as intended from Steph's original request.  It'll definitely ease any manual entry workflow we end up with.  Nice job!
Also excellent to have the enhancement following from Joanne's note above.  Those are the kinds of clean-ups that we don't always circle back for.  Thanks to both of you!
