### ISSUE TITLE
Allow creation of new Configuration Defaults after an initial Default(s) is created

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#277]
From Lucy on Demo v1.6.1 on 11/30/20:
lnorton  1:22 PM
Hi! Something that I've noticed when adding new configs is that once a default config event is created (on an AT), if you try to add a new default value or edit existing values it throws the following error: "Config default with this Conf def event and Config name already exists." This makes it a huge pain to add new configs because you have to delete all the previous settings and then re-enter the values.
...I was working on the ADCP on the GI riser (putting in the C/C/Cs in the correct places) but I've had the same problem on others as well.

I don't know if this affects Constant Defaults...

**Comment by cahearn** [comment]
Tested good for Dosta-D on Staging, Testing and Demo!  Still saw the original error on Demo for ADCP on GI01SUMO Riser (and GA), but thinking this may be limited to Demo ADCP:

![image](https://user-images.githubusercontent.com/14059724/102039330-7196db00-3d97-11eb-8277-e2806368d594.png)

**Comment by cahearn** [comment]
Lucy confirms general fix looks good.  Still finding the original error for ADCPS-N and FLORT-D on Demo GI01SUMO Assembly Template, Rev B.  @MarioCarloni , could you look into these for explanations for the quirkiness from your perspective?  Thanks!

**Comment by MarioCarloni** [comment]
Sure thing. Will look into this more deeply and report back.

**Comment by MarioCarloni** [comment]
After comparing several Instruments' Config Default Events on Demo server, incl DOSTA-D, ADCPS-N, FLORT-D, it seems there's some complicated sorting logic between several models that is throwing off the Config Default form. I believe I should be able to rework the models in order to resolve the issue.

For background, Config Name sorting differs between its model's default behavior, how the Names are loaded into the Config Default form, and how existing Config Default Values are handled. Django is incorrectly modifying the Config Name's "default" behavior (not to be confused with Config Defaults), and swapping data entry within the Config Default Event, then classifying the existing Config Defaults (newly swapped rows, driven by Names) as new copies, so when the form is submitted, Django throws an error that the Config Default/s already exists. It does, but on another row! However, if Config Names are entered alphabetically the first time (which they are for DOSTA-D), then all related downstream logic seems to work.

**Comment by cahearn** [comment]
Works great on Staging.  Demo hasn't received latest code update, so haven't been able to test original instigators.

**Comment by cahearn** [comment]
Although Staging represents the most recent 1.6.1 updates, testing on Demo with an earlier version of 1.6.1 also shows that this problem, specific to only a few Assembly Template entries, appears resolved.  Testing on Staging also confirms the most recent ver continues to work as expected.  Really great work, chasing this one down!

**Comment by cahearn** [comment]
Unfortunately, gotta revive this one :(
Found the same behavior as earlier on parts in Demo.  Haven;t been able to investigate further just yet, but hopefully we'll find an easy answer this time.  See below for example:
![image](https://user-images.githubusercontent.com/14059724/109700883-577fc400-7b60-11eb-924e-493ce148a965.png)

**Comment by cahearn** [comment]
After discussing ways to remedy this I attempted to delete one of the Config Events, intending to re-enter the configs.  Eventually, after working through several error screens and refreshing the page to clear dead links to the old Config Event, I was able to enter a new Config Event that behaved normally (was editable, etc.)

Here are a couple of the errors I found when trying to delete:

Landed here first:

![image](https://user-images.githubusercontent.com/14059724/110131324-065a1500-7d98-11eb-9025-dba40242acb4.png)


Then found this as I used the back button:

![image](https://user-images.githubusercontent.com/14059724/110131454-2689d400-7d98-11eb-9a9d-0fb99d4e40b3.png)

**Comment by cahearn** [comment]
Looks to be fixed!  Can't recreate any of these errors on `rdb-testing`.   Nice work!
