### ISSUE TITLE
Missing Edit Coefficient Metadata Button

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#304]
Steps to reproduce:

1. Create 2 Calibrations for a Part Template.
2. Create a Calibrations Csv file with 2 Calibrations which have the same value, .61  in this example.
3. Upload the Calibrations Csv.
4. Navigate to the Inventory Item and open the Calibration Coeff. History and click on the link.
5. Notice that the Edit Coefficient Metadata button is missing for "scalib2".

![meta](https://user-images.githubusercontent.com/65416034/104957330-f4651400-599b-11eb-88da-c3a8e0d01368.PNG)

If you then Edit the Coefficient Values and make them unique (.61 and .6125), the Edit Coeff. Metadata button is still missing for "scalib2".

![meta1](https://user-images.githubusercontent.com/65416034/104957563-62114000-599c-11eb-8ee0-630b42b45a8f.PNG)

Note that the Edit Coefficient Metadata button is not missing for the second value when you Upload a Calibration Csv and you do not have Calibrations previously defined for the Part Template.

Found on v1.6.3.

**Comment by MarioCarloni** [comment]
Hey @joannekoch, this may be relevant, but currently only Single and 1D Calibration Coefficients have editable Metadata, while 2D Calibrations do not. There is a related enhancement to add Metadata editing functionality for 2D Coefficients ( #97 ). Nonetheless I've begun trying to replicate the error using several Parts containing single, 1d, and 2d Calibration Coefficients, but have been thus far unsuccessful. I'm also unable to search for the Calibration file or Calibration Names referenced above on Staging (1.6.3).  

Which Parts and Inventory items did you test in order to uncover this error? Did the CSV files contain 2d Coefficients? Were either of the Calibration Name's data types set to 2D?

**Comment by joannekoch** [comment]
I was testing in my local environment using localhost:8000 and my own unique data.

My part template did have a 2D Calibration Coefficient:


<img width="500" alt="Mario" src="https://user-images.githubusercontent.com/65416034/106461608-fed6e180-6462-11eb-807b-62081f3dd2dd.PNG">

The Edit Coeff. Metadata button was missing for the 2D Coefficient, scalib2.

When I deleted the Calibration data for the Part and tried to import the csv file, I had not noticed that in this case the import created only Single Calibration Coefficients because the imported value was a single number = .61. Therefore, in this case the Edit Coeff. Metadata button was not missing.

So I think this problem is related to the 2D Coefficient not being editable yet.

**Comment by MarioCarloni** [comment]
Makes sense to me. Since #97 should take care of this issue, I'll go ahead and close the ticket.

Thanks for chasing this down!
