### ISSUE TITLE
Search: Actions for Cruise ID and Name Issues

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#306]
1. When choose **Search: Actions AND: Cruise ID or Cruise Name**, it is not obivious to the user that the search is only for Cruises that are Deployed on Builds. I thought the search would include cruises that were imported (not deployed on a build), but it did not.

2. The Search does not include Cruises that are on a Build in the Start Deployment State or the Burn-in State. This is not obivious to the user either.

3. If you Deploy a Build without a Cruise and then Edit the Deployment Details and set the "Cruise Deployed On" to a valid Cruise, the Search does not find the Deployed Cruise that was set after the Deployment.

Tested on v1.6.3.

**Comment by sbatchelder** [comment]
I think this has to do with there only being a limited number of kinds of Actions, and Actions associated with cruises are a function of actions taken on a Build. This is outside my wheelhouse so @ethanandrews or @MarioCarloni please chip in, I don't know how the Build/Cruise action interactions work. If we want to track things like "Cruise Import" then the list of action types would need to be expanded I think. As it stands, you are not seeing results for what you are seeking because I don't think Cruise Actions are being created for the use-cases you are describing. 

Solutions would be to either (A) note the limitation of the Action tracking system on the search page, or (B) add more Action events that encompass your/a user's expectation. It might also be that some actions erroneously not being recorded (or recorded for builds but not for cruises) which would indeed be a bug and I'd need Ethan or Mario's help with those systems to find/understand how to do that. 

I'm attaching below the list of available actions and action-object types for reference.

`File: roundabout/inventory/models.py`
```
ADD = 'add'
UPDATE = 'update'
LOCATIONCHANGE = 'locationchange'
SUBCHANGE = 'subchange'
ADDTOBUILD = 'addtobuild'
REMOVEFROMBUILD = 'removefrombuild'
STARTDEPLOYMENT = 'startdeployment'
REMOVEFROMDEPLOYMENT = 'removefromdeployment'
DEPLOYMENTBURNIN = 'deploymentburnin'
DEPLOYMENTTOFIELD = 'deploymenttofield'
DEPLOYMENTUPDATE = 'deploymentupdate'
DEPLOYMENTRECOVER = 'deploymentrecover'
DEPLOYMENTRETIRE = 'deploymentretire'
DEPLOYMENTDETAILS = 'deploymentdetails'
ASSIGNDEST = 'assigndest'
REMOVEDEST = 'removedest'
TEST = 'test'
NOTE = 'note'
HISTORYNOTE = 'historynote'
TICKET = 'ticket'
FIELDCHANGE = 'fieldchange'
FLAG = 'flag'
MOVETOTRASH = 'movetotrash'
RETIREBUILD = 'retirebuild'
REVIEWAPPROVE = 'reviewapprove'
EVENTAPPROVE = 'eventapprove'
CALCSVIMPORT = 'calcsvimport'
```

```
OBJECT_TYPES = (
    (BUILD, 'Build'),
    (INVENTORY, 'Inventory'),
    (DEPLOYMENT, 'Deployment'),
    (CALEVENT, 'Calibration Event'),
    (CONSTDEFEVENT, 'Constant Default Event'),
    (CONFEVENT, 'Configuration/Constant Event'),
    (CONFDEFEVENT, 'Configuration Default Event'),
    (COEFFNAMEEVENT, 'Coefficient Name Event'),
    (CONFNAMEEVENT, 'Configuration Name Event'),
)
DEPLOYMENT_TYPES = (
    (BUILD_DEPLOYMENT, 'Build Deployment'),
    (INVENTORY_DEPLOYMENT, 'Inventory Deployment'),

```

**Comment by ethanandrews** [comment]
I think @sbatchelder is basically correct on the options here. Cruises only have limited Actions tracked, pretty much just things related to Deployments. In general, only Inventory, Builds, Deployments, and then the Const/Config objects are treated as "primary" objects in RDB, so that they have full Action histories that are listed on their detail page, etc.

So if Cruises (or Vessels) need to be historically tracked in the same way, we'll need to add some functionality.

**Comment by joannekoch** [comment]
I'm ok with just clarifying the user interface for items 1 & 2 above. Instead of Cruise:ID and Cruise:Name in the search Action Type pulldown, perhaps we could use Deployed Cruise:ID and Deployed Cruise:Name.

I think item number 3. above still needs to be fixed.

**Comment by sbatchelder** [comment]
Hotfix commit above addresses 1&2 with clearer dropdown text.
(3) "If you Deploy a Build without a Cruise and then Edit the Deployment Details and set the "Cruise Deployed On" to a valid Cruise, the Search does not find the Deployed Cruise that was set after the Deployment" still in the works

**Comment by sbatchelder** [comment]
Deployment details changes and other deployment actions now records associated cruises where relevant. 
Changed in Action search "Deployed Cruise: ID" back to "Cruise: ID" as an action may now also record Recovery Cruises. 
There is still no Actions associated with importing/creating/changes made to a Cruise, only changes/updates to Deployments as they relate to Actions involving some associated Cruise (including deployment recoveries).

**Comment by joannekoch** [comment]
Since the pull down options for the Action Search include: 
Inventory: Serial Number
Inventory: Name

It may be a good idea to do the same with the Build options:
Build: Assembly
Build: Number
Build: Deployment Number
Build: Cruise ID
Build: Cruse Name

Then it is clear to the user that Cruises in the search are associated with Build Actions such as deployment and recovery.
It is also consistent with Inventory search options.

**Comment by cahearn** [comment]
All fixes worked great for me!  Cruise ID and Name searching now pulls results from all Builds, regardless of phase of Deployment function, or whether text was edited.  I think current wording in dropdowns is clear enough, given the improvements to search, but Joanne's most comment to add "Build:..." for clarification could be considered for later additions.  

Also, worth mentioning that because of expanding Cruise search as described, results return for metadata that were previously entered but have since been edited.  Could lead to confusion for casual users.
[Tested on Staging}
