### ISSUE TITLE
Search:Builds:Total Action Count and Exact = Blank throws ValueError

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#307]
Select **Search: Builds**. Select **Total Action Count**. Select **Exact** and leave the value field blank. A ValueError screen is thrown.

Please add field checking and display an error message to the user.

![valueerror](https://user-images.githubusercontent.com/65416034/105201734-3367a680-5b0f-11eb-9bcf-a9f65b165e46.PNG)

Release 1.6.3.

**Comment by cahearn** [comment]
We've got an error message!  Nicely done!

![image](https://user-images.githubusercontent.com/14059724/105798936-4c35e900-5f61-11eb-926d-2fa2f78764e0.png)

The first time I get an error (whether this one or the "Must use 'Exact' to search for 'empty'...") there is no check box portion.  Is this by design?  Seems close to the issue we're continually chasing down in #240.

If I mark the "Prevent..." checkbox and continue then the error message doesn't appear again, but the search doesn't return anything.  A page refresh allows the error message back.

**Comment by sbatchelder** [comment]
I think the checkbox option is added-in by the browser (if/when a page issues more than one notification).

Overall this seems like the correct kind of behavior: notifications are issued, a user can choose to mute them (standard browser security feature against notifications being spammed), and if they do then the warnings are not shown but an error-causing query is still prevented/not submitted.
