### ISSUE TITLE
CCC Approval: Homogenize Approval status logic

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#380]
Genericize CCC event approval functionality, so that any event requires 2 or more approvals in order to be fully approved.

**Comment by joannekoch** [comment]
Not working - depends on issue #403 being fixed.

**Comment by joannekoch** [comment]
There is one reviewer for this CCC event and this event requires approval.

![Capture](https://user-images.githubusercontent.com/65416034/127162165-08305ef0-0c1d-45d1-875d-62fa819871d6.PNG)

After approval, the "review requested" flag goes away indicating the event is approved. Therefore, this event does not require 2 or more approvals in order to be fully approved.

![Capture1](https://user-images.githubusercontent.com/65416034/127162287-4a66482f-628a-4827-ab9a-8dff603f123b.PNG)

**Comment by MarioCarloni** [comment]
Hi @joannekoch, the Event should display an "Approved" badge when at least 2 Users approve it. The "Review Requested" flag should display when the logged-in User has been marked as a Reviewer, and disappear when the logged-in User approves the Event. In the case where the logged-in User is viewing an Event, has not ben tagged as a Reviewer, and the Event has less than 2 Approvers, then the only badge displayed should be "In-Progress".
