### ISSUE TITLE
Search for Part Templates displays no revision for some Parts

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#433]
On rdb-testing.whoi.edu, Select Search->Part Templates.

Note that some Parts (not all) have '-' for a revision even though revision is a required field for a Part.

![Capture](https://user-images.githubusercontent.com/65416034/128906218-4423698e-9211-43c5-8127-5c78458c119f.PNG)

Note that the 2 Slot Backplane PCB has revision 'A', but a dash is displayed.

![Capture1](https://user-images.githubusercontent.com/65416034/128906231-87e2d4cd-55d4-4fa7-8ab5-ed884838c500.PNG)

**Comment by sbatchelder** [comment]
@joannekoch, I suspect part.revision is somehow not being recorded in certain situations. The `-` being displayed indicates that the field value is blank (but not null). Can you determine if this is happening on new parts, or imported parts? 
Here's a search to show all the blanks: https://rdb-testing.whoi.edu/search/parts?f=.0.revision&l=.0.exact&q=.0.

@ethanandrews, is the `revision` field on a Part model deprecated in favor of using Revision model?should part.revision be removed? 

@cahearn, should the revision field in the search display the most recent revision code, or list all a part's revisions?
```
class Part(models.Model):
    ...
    revision = models.CharField(max_length=100, blank=True)  # should we delete this
    ...

class Revision(models.Model):
    revision_code = models.CharField(default="A", ...)
    part = models.ForeignKey(Part, related_name="revisions", ...)
    ...
```

**Comment by ethanandrews** [comment]
The “revision” field on the Part model is definitely deprecated. Revision model is where it’s at! I think we can remove that old field entirely at this point.



From: Sidney Batchelder ***@***.***>
Date: Tuesday, August 10, 2021 at 2:07 PM
To: WHOIGit/ooicgsn-roundabout ***@***.***>
Cc: Ethan Andrews ***@***.***>, Mention ***@***.***>
Subject: Re: [WHOIGit/ooicgsn-roundabout] Search for Part Templates displays no revision for some Parts (#433)

@joannekoch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoannekoch&data=04%7C01%7Ceandrews%40whoi.edu%7C6beef612a5d3457a8c0508d95c29a8e6%7Cd44c5cc6d18c46cc8abd4fdf5b6e5944%7C0%7C0%7C637642156271233740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=t%2F5eEgYe8lmIZtpXI9CGBIqAb9TWIxwUjM%2BVpvRg4%2Bs%3D&reserved=0>, I suspect part.revision is somehow not being recorded in certain situations. The - being displayed indicates that the field value is blank (but not null). Can you determine if this is happening on new parts, or imported parts?
Here's a search to show all the blanks: https://rdb-testing.whoi.edu/search/parts?f=.0.revision&l=.0.exact&q=.0.

@ethanandrews<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fethanandrews&data=04%7C01%7Ceandrews%40whoi.edu%7C6beef612a5d3457a8c0508d95c29a8e6%7Cd44c5cc6d18c46cc8abd4fdf5b6e5944%7C0%7C0%7C637642156271243734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hfpp52DbiUvKw7qqe6z5mSP6rSD8RwAcvIeeVqTkArE%3D&reserved=0>, is the revision field on a Part model deprecated in favor of using Revision model?should part.revision be removed?

@cahearn<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcahearn&data=04%7C01%7Ceandrews%40whoi.edu%7C6beef612a5d3457a8c0508d95c29a8e6%7Cd44c5cc6d18c46cc8abd4fdf5b6e5944%7C0%7C0%7C637642156271243734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g9EyInv3nh7Aec%2B7Mozj0Lb3fALTi3vl8WoT9iM%2BxMM%3D&reserved=0>, should the revision field in the search display the most recent revision code, or list all a part's revisions?

class Part(models.Model):

    ...

    revision = models.CharField(max_length=100, blank=True)  # should we delete this

    ...



class Revision(models.Model):

    revision_code = models.CharField(default="A", ...)

    part = models.ForeignKey(Part, related_name="revisions", ...)

    ...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/WHOIGit/ooicgsn-roundabout/issues/433#issuecomment-896202962>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJPWKNSYMXWJN3QSTQLTWJDT4FTEFANCNFSM5B4RUPRQ&data=04%7C01%7Ceandrews%40whoi.edu%7C6beef612a5d3457a8c0508d95c29a8e6%7Cd44c5cc6d18c46cc8abd4fdf5b6e5944%7C0%7C0%7C637642156271253732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2fMrY2zGPl6mKmZkd8QRWvrvl3YBJvG1hl5zwfEAsYw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ceandrews%40whoi.edu%7C6beef612a5d3457a8c0508d95c29a8e6%7Cd44c5cc6d18c46cc8abd4fdf5b6e5944%7C0%7C0%7C637642156271253732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yjZK6bm78XicBYepzqQiwoJXROqL4jZgILAvtxzteIA%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Ceandrews%40whoi.edu%7C6beef612a5d3457a8c0508d95c29a8e6%7Cd44c5cc6d18c46cc8abd4fdf5b6e5944%7C0%7C0%7C637642156271263723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vy42BE2aKFW2YzVNySXjgD6SZC7xG1qbjTPeVcfB4w4%3D&reserved=0>.

**Comment by joannekoch** [comment]
All part revisions are now filled in when performing a Search for Part Templates. Fixed.
