### ISSUE TITLE
Address security issues with search/tag parameters

### ISSUE THREAD

**Issue by ethanandrews** [WHOIGit/ooicgsn-roundabout#487]
Hey @sbatchelder 

@joannekoch has run the OWASP Zap security testing tool against the RDB build and it found some issues with the handling of the query parameters in your Search and Tagging features. I think you just need to add some validation/sanitation to those query strings to avoid and Cross Site Scripting or Injection attacks. 

Full report is here:
https://drive.google.com/file/d/1OVHxIUhIqWAx083ZgsKEAtXXaEIFnS4X/view?usp=sharing

Look at issues 1 and 3 in the High Risk category in particular. Thanks!

**Comment by sbatchelder** [comment]
removed template calls to |escapejs in favor of |json_script
Some of the security risks I think was just the server throwing an error when an invalid value was being sent to it. like a string (malicious or benign) instead of an integer for a model id. I addressed this for search by defaulting such errors to either redirecting to a safe page, or returning an empty query.

**Comment by joannekoch** [comment]
ZAP Attack was run after these changes were incorporated. The report showed no High Risk Category alerts for the Search capability. The report can be found at: https://drive.google.com/file/d/1BHgtMxXamwSsiH_dncOAXgTQQybLbc-R/view?usp=sharing
