### ISSUE TITLE
Bulk Upload CSV Import: No Reviewers associated with Event on selection

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#493]
Prior to importing Bulk Upload files, a User can select Reviewers for the Event. An associated User should see a Review Requested badge on relevant Inventory Navtree items. However, no badge is shown. Please fix so that Reviewers are correctly associated with Bulk Upload Events, in order for Review Requested badges to correctly display from Inventory Navtree items.

**Comment by joannekoch** [comment]
Prior to importing Bulk Upload files, a User can select Reviewers for the Event. The associated User has a Review Requested badge on relevant Inventory Navtree items. This issue is fixed.

![Capture](https://user-images.githubusercontent.com/65416034/148112369-fcf66c61-f0e9-430d-b92f-2e51e4ee7b74.PNG)
