### ISSUE TITLE
Assembly Part: Reference Designators: Change Delete functionality to disassociate Assembly Parts from Reference Designator objects

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#501]
Change the deletion functionality for Reference Designator Events, so that on Delete, the association between Assembly Parts and Reference Designator objects is nullified. However, the Reference Designator objects should remain.

**Comment by joannekoch** [comment]
Steps to test:
1. Bulk Upload a RefDes csv file.
2. Add a RefDes from the list of available Ref Designators available in the pull down list to an Assembly.
3. Add the same RefDes above to another Assembly.
4. Dissociate the RefDes from the first Assembly.

Note that the RefDes item still exists on the second Assembly. Also, note that when adding a new RefDes to an Assembly that the RefDes in step 2 above is still available in the pull down list of Ref Designators.

This issue is working as tested in the above steps.
