### ISSUE TITLE
CSV Bulk Upload: Update associated Inventory Custom Fields from Asset Records

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#512]
When parsing Asset Record CSV's, if a row's Serial Number matches an existing Inventory item, update the Inventory Item's associated Custom Fields using attributes from the Asset Record row.

**Comment by joannekoch** [comment]
After uploading an Asset Record CSV, the Inventory's custom fields are NOT populated from the import. 
Note: the manufacturer and model are set because they were copied from the Part Template.

![Capture1](https://user-images.githubusercontent.com/65416034/153266809-cc5c156f-feb6-4b96-b6cd-689535e7fc71.PNG)


![Capture](https://user-images.githubusercontent.com/65416034/153268229-241ad6af-9b8c-49ed-b1b3-dc15acf80c84.PNG)

**Comment by MarioCarloni** [comment]
@joannekoch From the current release 1.7 branch, Inventory Custom Field Values are updated for the aforementioned Inventory item using the `sensor-bulk-load` Asset Record csv file. Since the items are updated within a Celery Task, this may be a Celery Task refresh issue. Reaching out to @ethanandrews and moving card back to RiP.

**Comment by joannekoch** [comment]
After creating ADCPS-J and importing sensor_bulk_load-AssetRecord.csv, no custom fields were created from the import file.  The above screen shots had the custom fields, but now they are missing

![Capture1](https://user-images.githubusercontent.com/65416034/169392502-a099fefe-328b-45fc-bda3-5486faf7d67e.PNG)
![Capture](https://user-images.githubusercontent.com/65416034/169392526-3a769ed0-b904-4527-8ed0-ccaff3d42909.PNG)
![Capture](https://user-images.githubusercontent.com/65416034/169393054-1f00ace5-a2cd-48ee-9f04-09a03449f4eb.PNG)

**Comment by joannekoch** [comment]
This issue is fixed and working.

Custom Fields are imported from uploaded the sensor_bulk_load-AssetRecord.csv:
![Capture3](https://user-images.githubusercontent.com/65416034/170269416-004e76a9-7766-4437-b8f0-b70d6a366f02.PNG)

Imported Custom Fields appear on the Part Specs Tab for the Inventory.

![Capture3](https://user-images.githubusercontent.com/65416034/170269624-953ccacd-44ff-4fde-9210-e04e7b03507e.PNG)
