### ISSUE TITLE
Bulk Upload: Generate Inventory items using new Asset Record field

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#528]
A new Part template-based field has been added to Bulk Asset Record files. The field can be leveraged to generate new Inventory items from matching Part items.

https://github.com/oceanzus/asset-management/tree/addcolumntest

**Comment by joannekoch** [comment]
Wasn't able to create Inventory item using new Asset Record field.

Created Part Template:
![Capture1](https://user-images.githubusercontent.com/65416034/161597596-00edb0c3-97f4-41dd-a6dd-253fd505c6b2.PNG)

Uploaded this sensor_bulk_load-AssetRecord.csv file with matching Part Number. Upload outcome was successful.

![Capture](https://user-images.githubusercontent.com/65416034/161597470-f91bb86a-cd98-4729-b7bd-a2470f1f9ca1.PNG)

Result: no inventory item was created. 

![Capture2](https://user-images.githubusercontent.com/65416034/161598606-3b2cc7ff-fc2f-4c15-afa9-d9794e934666.PNG)

**Comment by joannekoch** [comment]
An Inventory, 1336-00010-00000, was created when Part Number 1336-00010-00000 shown above was created by the user and then the sensor_bulk_load-AssetRecord.csv was uploaded. Wonderful!

@MarioCarloni, I noticed a few things. ADCPS-J was already created by the user before the import. The import created a new Part,  1336-00010-00000, with the same Part Number as ADCPS-J. The new part should not have been created since it already existed and you cannot have two Parts defined with the same Part Number.

![Capture](https://user-images.githubusercontent.com/65416034/163192556-0d68bdb3-b5aa-48a9-b582-e4e6a03f39ab.PNG)
![Capture1](https://user-images.githubusercontent.com/65416034/163192576-a9fecc6b-3f6a-4251-bcee-d74d0d03d7b9.PNG)

The Inventory was created in the Retired location. Is this the intent? The sensor_bulk_load-AssetRecord.csv file does not specify a location, nor does the Part Template, so I don't know how you would determine where to put it.

![Capture](https://user-images.githubusercontent.com/65416034/163193433-c15038df-77bd-416b-a450-6755e1a43ec2.PNG)

**Comment by joannekoch** [comment]
When ADCPS-J was already created by the user before the import, the import recognized that the Part (1336-00010-00000) was already created and did not create a new Part.

When the same sensor_bulk_load-AssetRecord.csv was uploaded twice, the upload recognized that both the Part and Inventory already existed and did not create a new Part and Inventory.

Works nicely!
