### ISSUE TITLE
Advanced Search testing

### ISSUE THREAD

**Issue by ethanandrews** [WHOIGit/ooicgsn-roundabout#63]
@rhmunier the new advanced search functionality is up on the testing server and ready for you to test. Let it rip.

**Comment by ethanandrews** [comment]
There's an issue with fresh installs and the django_tables2 module in the tables.py file. Django throws an error, possible that the tables module is trying to load db fields before they exist. This needs further testing.

**Comment by sbatchelder** [comment]
Fixed! It had to do with a db query that happened at the module level (not in a class or function). I placed the call inside a function/class and it should now be fine. Pushed the changes to a new branch: sidney-dev2

**Comment by ethanandrews** [comment]
Reopening so Rob can list bugs here

**Comment by sbatchelder** [comment]
Re location.root_type seeming empty. 
I think the database is being queried correctly and that location.root_type is typically not set. 
Rob mentioned that "Retired" seems to show up and, if allowed in search results, "Trash" is also shows up. I'll note that for both of these cases the location name is the same as the "root_type".

It looks to me like when something is retired or trashed, the location name and location root_type are both set, but otherwise "root type" for a given location instance is not explicitly set.

I'm just noticing that Location is an MPTT object; the root can probably be found by traversing the tree. Presumable the location at the end will feature to root. To be continued...

Short term, probably the easiest thing to do is to simply omit "root_type" from search and search results.

**Comment by ethanandrews** [comment]
Yes, let’s omit root_type from search results. That field is really just for organizing land/sea type distinctions, and is pretty much deprecated at this point.


On Apr 22, 2020, at 8:32 PM, Sidney Batchelder <notifications@github.com> wrote:

﻿

Re location.root_type seeming empty.
I think the database is being queried correctly and that location.root_type is typically not set.
Rob mentioned that "Retired" seems to show up and, if allowed in search results, "Trash" is also shows up. I'll note that for both of these cases the location name is the same as the "root_type".

It looks to me like when something is retired or trashed, the location name and location root_type are both set, but otherwise "root type" for a given location instance is not explicitly set.

I'm just noticing that Location is an MPTT object; the root can probably be found by traversing the tree. Presumable the location at the end will feature to root. To be continued...

Short term, probably the easiest thing to do is to simply omit "root_type" from search and search results.
