### ISSUE TITLE
Advanced Search Feedback

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#67]
Search is looking great!  Dare I say... Advanced even!!!

Here's a couple things I've found:

- Initial blank search return all items in inventory but subsequent blank searches returns this error: "Query textboxes cannot be left empty"
- Some functionality is lost compared to original search (ex: "Old Serial Number" field was part of search, now it's not)
- Searching "Note" is a search on Part Template Note.  While useful, search of the text from all "Note" actions is what we're really looking for.  Closest offered is searching on "Latest Action: Details," which works as expected, only returns from Notes that are the most recent action.
- Initial Search categories (Inventory; Parts; Builds; Assemblies) are confusing.  Could they be re-labeled and re-ordered as: Inventory: Builds; Part Templates; Assembly Templates      ?

**Comment by spetillo** [comment]
@sbatchelder Some more feedback here. Stuff in **bold** is stuff to address...

1. It looks like the original search dropdown in the upper right didn't get updated when the dropdown next to "Search:" in the upper-ish left got updated. Also, the "Search:" dropdown displays the old label (i.e., "Build" instead of Builds", "Part" instead of "Part Templates", "Assembly" instead of "Assembly Templates") after you make your selection. **Is there a way to make all of these dropdowns consistently show the same selections without hard-coding each one? These must be set in at least 3 places right now because they all show up as something different, but they should only need to be set in one place.**

2. A) "Notes & Details" only shows up for Inventory search. Good.
B) **Builds search shows "Notes" and "Detail" separately**, but I think these **should be a search on details only, also called "Notes & Details"**.
C) **Part search shows just "Note"**, which I assume searches the "Part Template Notes" field? I think this is different from searching on details, since there's no history "details" section to be searching on, so that's ok. **Please change this to "Notes" for consistency.**
D) Assembly search shows no way to search notes or details, though I don't see a way to put notes on assemblies, so I think that's ok.

3. Old Serial Number re-addition looks good. 

4. "Get All" search works.

**Comment by spetillo** [comment]
![Screenshot from 2020-05-08 14-23-06](https://user-images.githubusercontent.com/11924613/81439222-08cded00-913c-11ea-9a88-81e76c93da88.png)
Screenshot for Item 1 in my previous comment.

**Comment by sbatchelder** [comment]
(1) I can hard code these changes for now quickly. I'll look into parameterizing them. 
(2B) I can do that. I want to point out that there are both described in the Build model. Right now with the database from ooi-rdb 'm using, no build has either any Note or Details.
```
class Build(models.Model):
    ...
    build_notes = models.TextField(blank=True)
    detail = models.TextField(blank=True)
    ...
```
![image](https://user-images.githubusercontent.com/44208509/81440900-c8bc3980-913e-11ea-928a-d56a12957e15.png)

(2C) easy fix

**Comment by ethanandrews** [comment]
Hey Sidney, you can ignore the “detail” field for both Inventory and Build models. Those are used just as passthrough fields to simplify the generation of the notes for the Action model history.

**Comment by sbatchelder** [comment]
(1) continued...

Is this the third place you mentioned, @spetillo ?
![image](https://user-images.githubusercontent.com/44208509/81441248-6fa0d580-913f-11ea-9b84-42bac34d9d77.png)
If so, it looks like there ARE some form of parameterized label name for these but (a) it's not used everywhere/consistently and (b) but it renders as eg: "Assemblies" not "Assembly Templates" like you ask.
@ethanandrews, I found these template tags in base.html for the navbar. Where are these set? Also, is parameterizing and getting this right and consistent in all these three places a priority for this release?
```
<a class="nav-link" href="{% url 'inventory:inventory_home' %}">{{ label_inventory_app_plural }}</a>
<a class="nav-link" href="{% url 'builds:builds_home' %}">{{ label_builds_app_plural }}</a>

<div class="dropdown-menu" aria-labelledby="navbarTemplates">
  <a class="dropdown-item" href="{% url 'parts:parts_home' %}">Parts</a>
  <a class="dropdown-item" href="{% url 'assemblies:assemblies_home' %}">{{ label_assemblies_app_plural }}</a>
  <a class="dropdown-item" href="{% url 'locations:locations_home' %}">Locations</a>
```
Note how some text fields use {{ label_*_app_plural }} and other are hardcoded, like Parts and Locations, and how none of the Templates include "Templates" in the label. Understandable because they're under the Templates dropdown, but inconsistent with how you want it to appear in Search

**Comment by sbatchelder** [comment]
@ethanandrews 
Aha! okay!
I am going to keep build.build_notes then though. These are separate from build_actions.details.

I'm also renaming inventory_actions.details and build_actions.details to show up as "Latest Action: Notes" as I think that would make more sense to an end-user.

> Hey Sidney, you can ignore the “detail” field for both Inventory and Build models. Those are used just as passthrough fields to simplify the generation of the notes for the Action model history.

**Comment by ethanandrews** [comment]
Those are set in the environmental variables. The idea is that end users may want to change the default naming conventions for things like Assembly, Build, Deployment and Inventory. However, we decided there was no point in giving them that option for base things like Part and Location.

You can get the labels like this in .py files:
`# Get the app label names from the core utility functions
from roundabout.core.utils import set_app_labels
labels = set_app_labels()
`

**Comment by ethanandrews** [comment]
Yes, the Build notes field is a standalone general "note" field for Builds and should be included.

**Comment by spetillo** [comment]
1) OK, can we use `{{ label_assemblies_app_singular }} Templates` and `Parts Templates`... or can we set more environmental variables for these? If this isn't doable today, I could be willing to hard-code temporarily, but I don't love it.
1) continued...
 Nope, the third place is on the search page. Next to "Search:", when you click that dropdown the options are correct (e.g., "Part Templates"), but once you select something from the dropdown, the box says what the selection used to be (i.e., "Part")... I'll attach a screenshot in a sec.

2B) Yep, I see that now. Can we have Build Notes = "Build Notes" and Historical Details = "Notes & Details"?
For reference, there are Historical Details on some of our builds on Production, so those would be found by the search you had a screenshot of above. Screenshot:
![Screenshot from 2020-05-08 15-25-54](https://user-images.githubusercontent.com/11924613/81443253-19ce2c80-9143-11ea-9e7c-08dfe7ce9857.png)

**Comment by ethanandrews** [comment]
Yes, we can use  `{{ label_assemblies_app_singular }} Templates`. I'm not crazy about adding a new environmental variable for "Parts", as it would take quite a bit of work to update every place we use the term "Part" in the RDB templates and I think "Part" is a pretty simple term that we shouldn't give the user the temptation to screw around with.

**Comment by sbatchelder** [comment]
ok. updates are done and pushed to sidney-dev. should I put in a PR to develop... or to ooi-staging-rdb 
??

**Comment by ethanandrews** [comment]
PR to develop


On May 8, 2020, at 4:09 PM, Sidney Batchelder <notifications@github.com> wrote:

﻿

ok. updates are done and pushed to sidney-dev. should I put in a PR to develop... or to ooi-staging-rdb
??

**Comment by spetillo** [comment]
Re-posting comments from PR #69 here for reference, re: removing "Notes & Details" (historical action notes/details) search:

> After discussion with @sbatchelder about what exactly is happening, it appears that .details search only returns some of the historical notes. Since that is not going to work for us, we decided to remove the Notes & Details (historical action details) search option from the list for this release. This will allow us to spend more time addressing this issue.
> 
> We also decided that it would be best to give Actions their own search view that would allow users to see multiple returned historical action items per Inventory and/or Builds.
