### ISSUE TITLE
Advanced search error on OBS site

### ISSUE THREAD

**Issue by ethanandrews** [WHOIGit/ooicgsn-roundabout#72]
@sbatchelder Connor ran into a bug when demoing the advanced search on obs-rdb.whoi.edu. Search query with problem:

https://obs-rdb.whoi.edu/search/inventory?f=.0.part__name&l=.0.icontains&q=.0.q330

If you try to sort on any field besides the main Serial#, Name, Location, an error is thrown (like Unit Cost or whatever). I've added you to a user on that site so you can check it out, I'll slack you credentials. Have not seen this on other sites yet. 

<img width="1204" alt="Screen Shot 2020-05-15 at 11 02 54 AM" src="https://user-images.githubusercontent.com/39806262/82065151-bb9dce00-969b-11ea-8271-08c75cba3924.png">

**Comment by sbatchelder** [comment]
so i think I know what I can do to fix the bug but I can't recreate the error to check. would it be possible for me to obtain the obs database (a recent backup) to do testing?

**Comment by ethanandrews** [comment]
Yes, I can get you a copy of that. Probably in about an hour, away from computer at the moment.

On May 15, 2020, at 1:16 PM, Sidney Batchelder <notifications@github.com> wrote:

﻿

so i think I know what I can do to fix the bug but I can't recreate the error to check. would it be possible for me to obtain the obs database (a recent backup) to do testing?

**Comment by sbatchelder** [comment]
I think what's happening is that one or more user-defined-fields somewhere in the db has a field_value  None/null. These are the value's that are returned by `FieldValue.__str__()`. When the table is rendered, `__str__` is called on the udf and when None is returned instead of a string, it borks. 
So presumably this can be fixed by doing 

```
def __str__(self):
    return str(self.field_value)
```

This would show up as "None" in the table. We could also make it show up as an empty string `""`, `"null"`,` "—"`, `"<missing>"`. What do you think would be clearest to an end user?

This happens because `field_value = models.TextField(null=True, blank=True)`. 
A cursory look shows that most other models don't need to wrap whatever they return from `__str__()` with str() because the field returned does not have `null=True` in its definition.

**Comment by ethanandrews** [comment]
Ok, why don’t you try changing that field in the UDF model to be null=False, and see what happens? I slacked you a copy of the OBS DB.

If I try to sort on “Unit Cost”, I also get the error. That’s not a UDF field, it’s a DecimalField on the Part model.  Same issue?

**Comment by sbatchelder** [comment]
Got the obs database. Here's what it looks like with the fix.

Are we fine with those fields (ID, SN, other udf's) showing up as `"None"`?

![image](https://user-images.githubusercontent.com/44208509/82087232-b487b780-96bd-11ea-9b60-cef23984d686.png)

**Comment by ethanandrews** [comment]
I think for consistency, they should probably just be blank?

**Comment by sbatchelder** [comment]
it seems like changing `field_value = models.TextField(null=True, blank=True)` to `null=False` would prevent new blank FieldValues from being created as `None`, but a docker rebuild (which i think includes any migrations) with the above change does not seem to change the database instances where this is already the case. 
I've included `null=False` in my commits for Pull Request too for any new db created in the future.

**Comment by ethanandrews** [comment]
Great, thanks Sidney! Looks good at first glance, I'll test it out.
